var Promise = require('bluebird');
var db = appRequire('db');

module.exports = function() {
    return db('countries').truncate().then(function () {
        return Promise.all([
            db('countries').insert({'code': 'AF','name': 'Afghanistan'}),
            db('countries').insert({'code': 'AL','name': 'Albania'}),
            db('countries').insert({'code': 'DZ','name': 'Algeria'}),
            db('countries').insert({'code': 'AS','name': 'American Samoa'}),
            db('countries').insert({'code': 'AD','name': 'Andorra'}),
            db('countries').insert({'code': 'AO','name': 'Angola'}),
            db('countries').insert({'code': 'AI','name': 'Anguilla'}),
            db('countries').insert({'code': 'AQ','name': 'Antarctica'}),
            db('countries').insert({'code': 'AG','name': 'Antigua and Barbuda'}),
            db('countries').insert({'code': 'AR','name': 'Argentina'}),
            db('countries').insert({'code': 'AM','name': 'Armenia'}),
            db('countries').insert({'code': 'AW','name': 'Aruba'}),
            db('countries').insert({'code': 'AU','name': 'Australia'}),
            db('countries').insert({'code': 'AT','name': 'Austria'}),
            db('countries').insert({'code': 'AZ','name': 'Azerbaijan'}),
            db('countries').insert({'code': 'BS','name': 'Bahamas'}),
            db('countries').insert({'code': 'BH','name': 'Bahrain'}),
            db('countries').insert({'code': 'BD','name': 'Bangladesh'}),
            db('countries').insert({'code': 'BB','name': 'Barbados'}),
            db('countries').insert({'code': 'BY','name': 'Belarus'}),
            db('countries').insert({'code': 'BE','name': 'Belgium'}),
            db('countries').insert({'code': 'BZ','name': 'Belize'}),
            db('countries').insert({'code': 'BJ','name': 'Benin'}),
            db('countries').insert({'code': 'BM','name': 'Bermuda'}),
            db('countries').insert({'code': 'BT','name': 'Bhutan'}),
            db('countries').insert({'code': 'BO','name': 'Bolivia'}),
            db('countries').insert({'code': 'BA','name': 'Bosnia and Herzegovina'}),
            db('countries').insert({'code': 'BW','name': 'Botswana'}),
            db('countries').insert({'code': 'BV','name': 'Bouvet Island'}),
            db('countries').insert({'code': 'BR','name': 'Brazil'}),
            db('countries').insert({'code': 'IO','name': 'British Indian Ocean Territory'}),
            db('countries').insert({'code': 'VG','name': 'British Virgin Islands'}),
            db('countries').insert({'code': 'BN','name': 'Brunei Darussalam'}),
            db('countries').insert({'code': 'BG','name': 'Bulgaria'}),
            db('countries').insert({'code': 'BF','name': 'Burkina Faso'}),
            db('countries').insert({'code': 'BI','name': 'Burundi'}),
            db('countries').insert({'code': 'KH','name': 'Cambodia'}),
            db('countries').insert({'code': 'CM','name': 'Cameroon'}),
            db('countries').insert({'code': 'CA','name': 'Canada'}),
            db('countries').insert({'code': 'CV','name': 'Cape Verde'}),
            db('countries').insert({'code': 'KY','name': 'Cayman Islands'}),
            db('countries').insert({'code': 'CF','name': 'Central African Republic'}),
            db('countries').insert({'code': 'TD','name': 'Chad'}),
            db('countries').insert({'code': 'CL','name': 'Chile'}),
            db('countries').insert({'code': 'CN','name': 'China'}),
            db('countries').insert({'code': 'CX','name': 'Christmas Island'}),
            db('countries').insert({'code': 'CC','name': 'Cocos'}),
            db('countries').insert({'code': 'CO','name': 'Colombia'}),
            db('countries').insert({'code': 'KM','name': 'Comoros'}),
            db('countries').insert({'code': 'CD','name': 'Congo'}),
            db('countries').insert({'code': 'CG','name': 'Congo'}),
            db('countries').insert({'code': 'CK','name': 'Cook Islands'}),
            db('countries').insert({'code': 'CR','name': 'Costa Rica'}),
            db('countries').insert({'code': 'CI','name': 'Cote D\'Ivoire'}),
            db('countries').insert({'code': 'CU','name': 'Cuba'}),
            db('countries').insert({'code': 'CY','name': 'Cyprus'}),
            db('countries').insert({'code': 'CZ','name': 'Czech Republic'}),
            db('countries').insert({'code': 'DK','name': 'Denmark'}),
            db('countries').insert({'code': 'DJ','name': 'Djibouti'}),
            db('countries').insert({'code': 'DM','name': 'Dominica'}),
            db('countries').insert({'code': 'DO','name': 'Dominican Republic'}),
            db('countries').insert({'code': 'EC','name': 'Ecuador'}),
            db('countries').insert({'code': 'EG','name': 'Egypt'}),
            db('countries').insert({'code': 'SV','name': 'El Salvador'}),
            db('countries').insert({'code': 'GQ','name': 'Equatorial Guinea'}),
            db('countries').insert({'code': 'ER','name': 'Eritrea'}),
            db('countries').insert({'code': 'EE','name': 'Estonia'}),
            db('countries').insert({'code': 'ET','name': 'Ethiopia'}),
            db('countries').insert({'code': 'FO','name': 'Faeroe Islands'}),
            db('countries').insert({'code': 'FK','name': 'Falkland Islands'}),
            db('countries').insert({'code': 'FJ','name': 'Fiji'}),
            db('countries').insert({'code': 'FI','name': 'Finland'}),
            db('countries').insert({'code': 'FR','name': 'France'}),
            db('countries').insert({'code': 'GF','name': 'French Guiana'}),
            db('countries').insert({'code': 'PF','name': 'French Polynesia'}),
            db('countries').insert({'code': 'TF','name': 'French Southern Territories'}),
            db('countries').insert({'code': 'GA','name': 'Gabon'}),
            db('countries').insert({'code': 'GM','name': 'Gambia'}),
            db('countries').insert({'code': 'GE','name': 'Georgia'}),
            db('countries').insert({'code': 'DE','name': 'Germany'}),
            db('countries').insert({'code': 'GH','name': 'Ghana'}),
            db('countries').insert({'code': 'GI','name': 'Gibraltar'}),
            db('countries').insert({'code': 'GR','name': 'Greece'}),
            db('countries').insert({'code': 'GL','name': 'Greenland'}),
            db('countries').insert({'code': 'GD','name': 'Grenada'}),
            db('countries').insert({'code': 'GP','name': 'Guadaloupe'}),
            db('countries').insert({'code': 'GU','name': 'Guam'}),
            db('countries').insert({'code': 'GT','name': 'Guatemala'}),
            db('countries').insert({'code': 'GN','name': 'Guinea'}),
            db('countries').insert({'code': 'GW','name': 'Guinea-Bissau'}),
            db('countries').insert({'code': 'GY','name': 'Guyana'}),
            db('countries').insert({'code': 'HT','name': 'Haiti'}),
            db('countries').insert({'code': 'HM','name': 'Heard and McDonald Islands'}),
            db('countries').insert({'code': 'VA','name': 'Holy See'}),
            db('countries').insert({'code': 'HN','name': 'Honduras'}),
            db('countries').insert({'code': 'HK','name': 'Hong Kong'}),
            db('countries').insert({'code': 'HR','name': 'Hrvatska'}),
            db('countries').insert({'code': 'HU','name': 'Hungary'}),
            db('countries').insert({'code': 'IS','name': 'Iceland'}),
            db('countries').insert({'code': 'IN','name': 'India'}),
            db('countries').insert({'code': 'ID','name': 'Indonesia'}),
            db('countries').insert({'code': 'IR','name': 'Iran'}),
            db('countries').insert({'code': 'IQ','name': 'Iraq'}),
            db('countries').insert({'code': 'IE','name': 'Ireland'}),
            db('countries').insert({'code': 'IL','name': 'Israel'}),
            db('countries').insert({'code': 'IT','name': 'Italy'}),
            db('countries').insert({'code': 'JM','name': 'Jamaica'}),
            db('countries').insert({'code': 'JP','name': 'Japan'}),
            db('countries').insert({'code': 'JO','name': 'Jordan'}),
            db('countries').insert({'code': 'KZ','name': 'Kazakhstan'}),
            db('countries').insert({'code': 'KE','name': 'Kenya'}),
            db('countries').insert({'code': 'KI','name': 'Kiribati'}),
            db('countries').insert({'code': 'KP','name': 'Korea'}),
            db('countries').insert({'code': 'KR','name': 'Korea'}),
            db('countries').insert({'code': 'KW','name': 'Kuwait'}),
            db('countries').insert({'code': 'KG','name': 'Kyrgyz Republic'}),
            db('countries').insert({'code': 'LA','name': 'Lao People\'s Democratic Republic'}),
            db('countries').insert({'code': 'LV','name': 'Latvia'}),
            db('countries').insert({'code': 'LB','name': 'Lebanon'}),
            db('countries').insert({'code': 'LS','name': 'Lesotho'}),
            db('countries').insert({'code': 'LR','name': 'Liberia'}),
            db('countries').insert({'code': 'LY','name': 'Libyan Arab Jamahiriya'}),
            db('countries').insert({'code': 'LI','name': 'Liechtenstein'}),
            db('countries').insert({'code': 'LT','name': 'Lithuania'}),
            db('countries').insert({'code': 'LU','name': 'Luxembourg'}),
            db('countries').insert({'code': 'MO','name': 'Macao'}),
            db('countries').insert({'code': 'MK','name': 'Macedonia'}),
            db('countries').insert({'code': 'MG','name': 'Madagascar'}),
            db('countries').insert({'code': 'MW','name': 'Malawi'}),
            db('countries').insert({'code': 'MY','name': 'Malaysia'}),
            db('countries').insert({'code': 'MV','name': 'Maldives'}),
            db('countries').insert({'code': 'ML','name': 'Mali'}),
            db('countries').insert({'code': 'MT','name': 'Malta'}),
            db('countries').insert({'code': 'MH','name': 'Marshall Islands'}),
            db('countries').insert({'code': 'MQ','name': 'Martinique'}),
            db('countries').insert({'code': 'MR','name': 'Mauritania'}),
            db('countries').insert({'code': 'MU','name': 'Mauritius'}),
            db('countries').insert({'code': 'YT','name': 'Mayotte'}),
            db('countries').insert({'code': 'MX','name': 'Mexico'}),
            db('countries').insert({'code': 'FM','name': 'Micronesia'}),
            db('countries').insert({'code': 'MD','name': 'Moldova'}),
            db('countries').insert({'code': 'MC','name': 'Monaco'}),
            db('countries').insert({'code': 'MN','name': 'Mongolia'}),
            db('countries').insert({'code': 'MS','name': 'Montserrat'}),
            db('countries').insert({'code': 'MA','name': 'Morocco'}),
            db('countries').insert({'code': 'MZ','name': 'Mozambique'}),
            db('countries').insert({'code': 'MM','name': 'Myanmar'}),
            db('countries').insert({'code': 'NA','name': 'Namibia'}),
            db('countries').insert({'code': 'NR','name': 'Nauru'}),
            db('countries').insert({'code': 'NP','name': 'Nepal'}),
            db('countries').insert({'code': 'AN','name': 'Netherlands Antilles'}),
            db('countries').insert({'code': 'NL','name': 'Netherlands'}),
            db('countries').insert({'code': 'NC','name': 'New Caledonia'}),
            db('countries').insert({'code': 'NZ','name': 'New Zealand'}),
            db('countries').insert({'code': 'NI','name': 'Nicaragua'}),
            db('countries').insert({'code': 'NE','name': 'Niger'}),
            db('countries').insert({'code': 'NG','name': 'Nigeria'}),
            db('countries').insert({'code': 'NU','name': 'Niue'}),
            db('countries').insert({'code': 'NF','name': 'Norfolk Island'}),
            db('countries').insert({'code': 'MP','name': 'Northern Mariana Islands'}),
            db('countries').insert({'code': 'NO','name': 'Norway'}),
            db('countries').insert({'code': 'OM','name': 'Oman'}),
            db('countries').insert({'code': 'PK','name': 'Pakistan'}),
            db('countries').insert({'code': 'PW','name': 'Palau'}),
            db('countries').insert({'code': 'PS','name': 'Palestinian Territory'}),
            db('countries').insert({'code': 'PA','name': 'Panama'}),
            db('countries').insert({'code': 'PG','name': 'Papua New Guinea'}),
            db('countries').insert({'code': 'PY','name': 'Paraguay'}),
            db('countries').insert({'code': 'PE','name': 'Peru'}),
            db('countries').insert({'code': 'PH','name': 'Philippines'}),
            db('countries').insert({'code': 'PN','name': 'Pitcairn Island'}),
            db('countries').insert({'code': 'PL','name': 'Poland'}),
            db('countries').insert({'code': 'PT','name': 'Portugal'}),
            db('countries').insert({'code': 'PR','name': 'Puerto Rico'}),
            db('countries').insert({'code': 'QA','name': 'Qatar'}),
            db('countries').insert({'code': 'RE','name': 'Reunion'}),
            db('countries').insert({'code': 'RO','name': 'Romania'}),
            db('countries').insert({'code': 'RU','name': 'Russian Federation'}),
            db('countries').insert({'code': 'RW','name': 'Rwanda'}),
            db('countries').insert({'code': 'SH','name': 'St. Helena'}),
            db('countries').insert({'code': 'KN','name': 'St. Kitts and Nevis'}),
            db('countries').insert({'code': 'LC','name': 'St. Lucia'}),
            db('countries').insert({'code': 'PM','name': 'St. Pierre and Miquelon'}),
            db('countries').insert({'code': 'VC','name': 'St. Vincent and the Grenadines'}),
            db('countries').insert({'code': 'WS','name': 'Samoa'}),
            db('countries').insert({'code': 'SM','name': 'San Marino'}),
            db('countries').insert({'code': 'ST','name': 'Sao Tome and Principe'}),
            db('countries').insert({'code': 'SA','name': 'Saudi Arabia'}),
            db('countries').insert({'code': 'SN','name': 'Senegal'}),
            db('countries').insert({'code': 'CS','name': 'Serbia and Montenegro'}),
            db('countries').insert({'code': 'SC','name': 'Seychelles'}),
            db('countries').insert({'code': 'SL','name': 'Sierra Leone'}),
            db('countries').insert({'code': 'SG','name': 'Singapore'}),
            db('countries').insert({'code': 'SK','name': 'Slovakia'}),
            db('countries').insert({'code': 'SI','name': 'Slovenia'}),
            db('countries').insert({'code': 'SB','name': 'Solomon Islands'}),
            db('countries').insert({'code': 'SO','name': 'Somalia'}),
            db('countries').insert({'code': 'ZA','name': 'South Africa'}),
            db('countries').insert({'code': 'GS','name': 'South Georgia and the South Sandwich Islands'}),
            db('countries').insert({'code': 'ES','name': 'Spain'}),
            db('countries').insert({'code': 'LK','name': 'Sri Lanka'}),
            db('countries').insert({'code': 'SD','name': 'Sudan'}),
            db('countries').insert({'code': 'SR','name': 'Suriname'}),
            db('countries').insert({'code': 'SJ','name': 'Svalbard & Jan Mayen Islands'}),
            db('countries').insert({'code': 'SZ','name': 'Swaziland'}),
            db('countries').insert({'code': 'SE','name': 'Sweden'}),
            db('countries').insert({'code': 'CH','name': 'Switzerland'}),
            db('countries').insert({'code': 'SY','name': 'Syrian Arab Republic'}),
            db('countries').insert({'code': 'TW','name': 'Taiwan'}),
            db('countries').insert({'code': 'TJ','name': 'Tajikistan'}),
            db('countries').insert({'code': 'TZ','name': 'Tanzania'}),
            db('countries').insert({'code': 'TH','name': 'Thailand'}),
            db('countries').insert({'code': 'TL','name': 'Timor-Leste'}),
            db('countries').insert({'code': 'TG','name': 'Togo'}),
            db('countries').insert({'code': 'TK','name': 'Tokelau'}),
            db('countries').insert({'code': 'TO','name': 'Tonga'}),
            db('countries').insert({'code': 'TT','name': 'Trinidad and Tobago'}),
            db('countries').insert({'code': 'TN','name': 'Tunisia'}),
            db('countries').insert({'code': 'TR','name': 'Turkey'}),
            db('countries').insert({'code': 'TM','name': 'Turkmenistan'}),
            db('countries').insert({'code': 'TC','name': 'Turks and Caicos Islands'}),
            db('countries').insert({'code': 'TV','name': 'Tuvalu'}),
            db('countries').insert({'code': 'VI','name': 'US Virgin Islands'}),
            db('countries').insert({'code': 'UG','name': 'Uganda'}),
            db('countries').insert({'code': 'UA','name': 'Ukraine'}),
            db('countries').insert({'code': 'AE','name': 'United Arab Emirates'}),
            db('countries').insert({'code': 'GB','name': 'United Kingdom of Great Britain & N. Ireland'}),
            db('countries').insert({'code': 'UM','name': 'United States Minor Outlying Islands'}),
            db('countries').insert({'code': 'US','name': 'United States of America'}),
            db('countries').insert({'code': 'UY','name': 'Uruguay'}),
            db('countries').insert({'code': 'UZ','name': 'Uzbekistan'}),
            db('countries').insert({'code': 'VU','name': 'Vanuatu'}),
            db('countries').insert({'code': 'VE','name': 'Venezuela'}),
            db('countries').insert({'code': 'VN','name': 'Viet Nam'}),
            db('countries').insert({'code': 'WF','name': 'Wallis and Futuna Islands'}),
            db('countries').insert({'code': 'EH','name': 'Western Sahara'}),
            db('countries').insert({'code': 'YE','name': 'Yemen'}),
            db('countries').insert({'code': 'ZM','name': 'Zambia'}),
            db('countries').insert({'code': 'ZW','name': 'Zimbabwe'})
        ]);
    });
};